### ISSUE TITLE
Unintentional split

### ISSUE THREAD

**Issue by Traviktox** [UNHchabo/AutoSplitters#13]
Hello,
when you enter the teleport tube from oasis (https://wiki.supermetroid.run/Oasis), then there is an unintentional split.

**Comment by InsaneFirebat** [comment]
This was intentional.
"Split on entering Toilet Bowl from either direction"

Edit: Nevermind, I assume you mean it split without the "Toilet" setting enabled after seeing the latest pull request (Pull#12)

**Comment by UNHchabo** [comment]
Yeah, this looks to have been fixed just before you filed it:
https://github.com/UNHchabo/AutoSplitters/commit/2d96abdde38f75b698b903ebfaef3fd59a656a2d
