### ISSUE TITLE
Support for Snes9X version 1.57?

### ISSUE THREAD

**Issue by 123jrf** [UNHchabo/AutoSplitters#2]
I just upgraded my Snes9X to the latest version, and the autosplitter doesn't work. The readme says it only works with versions up through 1.56 right now. Will v1.57 support be happening soon?

**Comment by DarkXoa** [comment]
If you have any experience with CheatEngine, the most important part to adding support for a new emulator is finding the memory offset to where the emulator stores WRAM. If you can figure that out, Chabo should be able to get it working for you fairly quickly.

**Comment by UNHchabo** [comment]
Thanks to Spiraster finding the offsets, I've added support for Snes9x 1.57 and 1.58.

**Comment by UNHchabo** [comment]
Here's the commit adding this: https://github.com/UNHchabo/AutoSplitters/commit/5598fc58c3ee4c360cc3b34ac61db8de192650e3
